blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
fn_params_layout = "Vertical"
fn_single_line = false
hard_tabs = true
format_strings = true
normalize_comments = true
reorder_imports = true
indent_style = "Block"
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
newline_style = "Unix"
normalize_doc_attributes = true
use_field_init_shorthand = true
version = "Two"
wrap_comments = true